config/routes.rb
Storytime::Application.routes.draw do
  root :to => "story_cards#index"
  
  resources :users

  get "/signin" => "sessions#new", :as => "signin"
  delete '/signout' => "sessions#destroy", :as => "signout"
  post "/sessions" => "sessions#create"

  resources :story_cards do
    get "reply" => "story_cards#reply", :on => :member
    get "replies" => "story_cards#replies", :on => :member
    get 'vote/:value' => "story_cards#vote", :on => :member, :as => "vote"
  end
end

app/models/story_card.rb
class StoryCard < ActiveRecord::Base
  attr_accessible :content, :user_id, :parent_id

  has_many :votes
  belongs_to :story_card, :foreign_key => :parent_id
  belongs_to :user

  validates :content, :length => {:maximum => 140}, :presence => true

  before_save :clean_whitespace



  def self.main_threads
    now = Time.now
    StoryCard.select{|c| c.parent_id == nil}.sort_by{|card| [-card.score, now - card.created_at] }
  end

  def replies
    StoryCard.where("parent_id = ?", self.id).sort{|a,b| b.score <=> a.score}
  end

  def total_reply_count
    count = 0
    children = [self.id]
    while not children.empty?
      current = StoryCard.find children.pop
      count += 1
      children += current.replies.map {|r| r.id}
    end
    count
  end

  def absolute_parent
    current_id = self.id
    found = self

    while found.parent_id
      current_id = found.parent_id
      found = StoryCard.find(found.parent_id)
    end 

    StoryCard.find current_id
  end

  def upvotes_count
    Vote.where(:story_card_id => self.id, :value => 1).count
  end

  def downvotes_count
    Vote.where(:story_card_id => self.id, :value => -1).count
  end

  def score
    # This is horrible
    upvotes_count - downvotes_count
  end

  private
  def clean_whitespace
    # self.content = self.content.tr("\n\r", "")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :name, :password, :password_confirmation

  has_many :story_cards
  has_many :votes

  validates :name, :format => { :with => /^[a-zA-Z0-9\-_]+$/ }, :uniqueness => true
  validates :password, :presence => true
  validates :password_confirmation, :presence => true

  before_save :generate_token

  def update_token
    token = SecureRandom.base64(64)
    update_attribute(:token, token)
  end

  def upvote_count
    StoryCard.where(:user_id => self.id).inject(0) { |sum, card| sum += card.upvotes_count }
  end

  def downvote_count
    StoryCard.where(:user_id => self.id).inject(0) { |sum, card| sum += card.downvotes_count }
  end

  private 

  def generate_token
    self.token = SecureRandom.base64 64
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :story_card_id, :user_id, :value

  belongs_to :user
  belongs_to :story_card


  before_save :normalize_value

  def self.by_user_id_and_story_card_id user_id, story_card_id 
    where(:user_id => user_id).where(:story_card_id => story_card_id).limit(1).first
  end

  private

  def normalize_value
    self.value /= self.value.abs unless self.value == 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find_by_token(session[:user_token]) if session[:user_token]
  end

  def signout
    @current_user = nil
    session[:user_token] = nil
  end

  def signed_in?
    !!session[:user_token]
  end

  helper_method :current_user
  helper_method :signed_in?
  helper_method :signout
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    respond_to do |format|
      puts params
      @user = User.find_by_name params[:name]
      if @user && @user.authenticate(params[:password])
        @user.update_token

        format.html do
          session[:user_token] = @user.token
          redirect_to root_path
        end

        format.json
        format.xml
      else
        format.html do
          flash.now.alert = "Invalid email or password"
          render "new"
        end

        error_hash = {:error => "username or password is incorrect"}
        format.json { render :json => error_hash }
        format.xml { render :xml => error_hash }
      end


    end

  end

  def destroy
    signout
    # maybe destroy token
    redirect_to root_path
  end
end

app/controllers/story_cards_controller.rb
class StoryCardsController < ApplicationController

  before_filter :load_user, :except => :index

  def index
    @story_cards = StoryCard.main_threads
    respond_to do |format|
      format.html
      format.json
      format.xml
    end
  end

  def replies
    @story_card = StoryCard.find params[:id]
    @story_cards = @story_card.replies
    respond_to do |format|
      format.html 
      format.json
      format.xml

      render "index" and return
    end
  end

  def show
    @story_card = StoryCard.find params[:id]
  end

  def new
    @story_card = StoryCard.new
  end

  def create
    puts params
    @story_card = StoryCard.new params[:story_card]
    @story_card.user_id = @user.id

    respond_to do |format|
      if @story_card.save
        format.html { redirect_to @story_card.absolute_parent }
        format.json
        format.xml
      else
        format.html do
          flash.error = "Shit"
          redirect_to root_path
        end
        format.json {render :json => {:errors => @story_card.errors.full_messages}}
        format.xml {render :xml => {:errors => @story_card.errors.full_messages}}
        
      end
    end  
    
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def reply
    @parent = StoryCard.find params[:id]
    @story_card = StoryCard.new
    @story_card.parent_id = @parent.id
  end

  def vote
    value = params[:value]
    story_card = StoryCard.find params[:id]

    @vote = Vote.by_user_id_and_story_card_id(@user.id, story_card.id)
    if @vote
      @vote.update_attribute(:value, value)
    else
      @vote = Vote.create(:user_id => @user.id, :story_card_id => story_card.id, :value => value)
    end

    respond_to do |format|
      format.json {render :json => {:value => value, :story_card_id => story_card.id} }
    end

  end


  private
  def load_user
    puts params
    if request.format.json? || request.format.xml? 
      request_sym = request.format.to_s.split("/")[-1].to_sym
      if params.has_key?(:token)
        # Continue...
        @user = User.find_by_token params[:token]
        render request_sym => { :error => "No user with toke nexists"} if @user.nil?
      else
        #Render errors
        render request_sym => { :error => "You must provide an API token"}
      end
    else
      if signed_in?
        @user = current_user
      else
        redirect_to root_path
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :check_current_user, :only => [:new, :create]

  def index
  end

  def show
    if params[:id].to_i == 0
      @user = User.find_by_name params[:id]
    else
      @user = User.find
    end

    respond_to do |format|

      if @user
        format.html
        format.json
        format.xml
      else
        error = "That user does not exist"
        format.json { render :json => {:error => error }}
        format.xml { render :xml => {:error => error }}
        format.html {redirect_to root_path, :notice => error }
      end

    end
  end

  def new
    @user = User.new
  end

  def create
    respond_to do |format|
      puts params
      @user = User.new params[:user]
      
      if @user.save
        format.html do 
          session[:user_token] = @user.token
          redirect_to root_path
        end

        format.json
        format.xml
        
      else
        format.html { render "new" }
        format.json { render :json => { :errors => @user.errors.full_messages.to_json} }
        format.xml { render :xml => { :errors => @user.errors.full_messages.to_xml} }
      end

    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def check_current_user
    redirect_to root_path unless current_user.nil?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/story_cards_helper.rb
module StoryCardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Storytime" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>



    <div class="container">
      <div class="page-header">
        <h1><%= link_to "StoryTime!", root_path %> <small>what time is it?</small></h1>
        
        <div class='signin'>
          <% unless signed_in? %>
            <%= link_to "Create a account", new_user_path %>
            or
            <%= link_to "Sign in", signin_path %>
          <% else %>
            <%= link_to "Tell me something", new_story_card_path, :class => %w(btn btn-success) %>
            Signed in as <strong><%= current_user.name %></strong> / <%= link_to "Signout", signout_path, :method => :delete %>
          <% end %>
        </div>
      </div>

       <%= yield %>
      
      <footer>
        
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/story_cards/_form.html.erb
<%= simple_form_for @story_card do |f| %>
  <%= f.input :parent_id, :as => :hidden %>
  <%= f.input :content, :as => :text, :input_html => {rows:5} %>
  <%= f.submit %>
<% end %>

app/views/story_cards/_story_card.html.erb
<div class="score"><%= story_card.upvotes_count %> | <%= story_card.downvotes_count %></div>
<div class="content">
  <%= story_card.content %>
</div>

<div class="actions">
  <%= link_to "reply", reply_story_card_path(story_card) %>
  <%= link_to "⇧", vote_story_card_path(story_card,1), :remote => true %>
  <%= link_to "↓", vote_story_card_path(story_card,-1), :remote => true %>
</div>

<div class="replies">
  <%= render story_card.replies %>
</div>

app/views/story_cards/create.html.erb
<h1>StoryCard#create</h1>
<p>Find me in app/views/story_card/create.html.erb</p>

app/views/story_cards/destroy.html.erb
<h1>StoryCard#destroy</h1>
<p>Find me in app/views/story_card/destroy.html.erb</p>

app/views/story_cards/edit.html.erb
<h1>StoryCard#edit</h1>
<p>Find me in app/views/story_card/edit.html.erb</p>

<%= render "form" %>

app/views/story_cards/index.html.erb
<div class="row">
  <% @story_cards.each do |story_card| %>
    <div class="span2 story-card">
      <div class="content">
        <%= story_card.content%>
      </div>
      <%= link_to "Read on! (#{story_card.total_reply_count})", story_card_path(story_card) %>
    </div>
  <% end %>
</div>

app/views/story_cards/new.html.erb
<%= render "form" %>

app/views/story_cards/reply.html.erb
<h1>Replying to</h1>

<%= render @parent %>
<%= render "form" %>

app/views/story_cards/show.html.erb
<%= render @story_card %>

app/views/story_cards/update.html.erb
<h1>StoryCard#update</h1>
<p>Find me in app/views/story_card/update.html.erb</p>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name, :label => "Username" %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<%= render "user" %>